### ISSUE TITLE
Couple of thoughts about colors

### ISSUE THREAD

**Issue by xbladesub** [LunarVim/horizon.nvim#3]
I really like this color scheme, however I think there are a few places where the colors could be better (compared to the navrasu/onedark color scheme). Should the colors be different here?
![imgonline-com-ua-twotoone-SICvWSdarpC](https://user-images.githubusercontent.com/45129790/182061414-e24b0e59-6301-432e-9335-a3dafada21cc.jpg)

![imgonline-com-ua-twotoone-3T73LUzhlp3uaEMy](https://user-images.githubusercontent.com/45129790/182061426-a35bc36d-6ec7-4026-9ee1-32e2729f5907.jpg)

**Comment by akinsho** [comment]
>  (compared to the navrasu/onedark color scheme)

Not sure comparison to another colorscheme is right here, since I don't think an aim of a port of the horizon theme should be compared to a pretty different theme.

Although I agree that there's, arguably, an issue. I've seen whilst using other themes that were ported to neovim that `Variable` gets highlighted which `nvim-treesitter` links to `TSVariable` meaning that you end with a whole file that has that specific colour since variables are super common. I think a default exception for all themes should be to not highlight `TSVariable` as anything other than `Normal` (IMO ofc), unless it's a special variable like `variable.builtin` → `TSVariableBuiltin`

A "fix" I'm using personally is to set `TSVariable` to match `Normal` 🤷🏿

**Comment by akinsho** [comment]
For posterity, think I was wrong about this. I do think in most cases highlighting TSVariable is noisy, but although it doesn't use treesitter, so the effect isn't really the same, vscode's version of the theme does use this much red. So I actually think this is probably a true to life replication of the theme, I opened a few files in both editors to check.
